"use strict";(self.webpackChunkzell_chaos=self.webpackChunkzell_chaos||[]).push([[8130],{8039:(e,t,n)=>{n.r(t),n.d(t,{assets:()=>l,contentTitle:()=>i,default:()=>d,frontMatter:()=>o,metadata:()=>a,toc:()=>h});var a=n(85091),s=n(74848),r=n(28453);const o={layout:"posts",title:"Corrupted Snapshot Experiment Investigation",date:new Date("2021-04-29T00:00:00.000Z"),categories:["chaos_experiment","broker","snapshots"],tags:["availability"],authors:"zell"},i="Chaos Day Summary",l={authorsImageUrls:[void 0]},h=[{value:"Chaos Experiment",id:"chaos-experiment",level:2},{value:"Experiment",id:"experiment",level:3},{value:"Found Bugs",id:"found-bugs",level:2}];function c(e){const t={a:"a",code:"code",em:"em",h2:"h2",h3:"h3",img:"img",li:"li",p:"p",pre:"pre",strong:"strong",ul:"ul",...(0,r.R)(),...e.components};return(0,s.jsxs)(s.Fragment,{children:[(0,s.jsxs)(t.p,{children:["A while ago we have written an experiment, which should verify that followers are not able to become leader, if they have a corrupted snapshot. You can find that specific experiment ",(0,s.jsx)(t.a,{href:"https://github.com/zeebe-io/zeebe-chaos/tree/master/chaos-experiments/helm/snapshot-corruption",children:"here"}),". This experiment was executed regularly against Production-M and Production-S Camunda Cloud cluster plans. With the latest changes, in the upcoming 1.0 release, we changed some behavior in regard to detect snapshot corruption on followers."]}),"\n",(0,s.jsxs)(t.p,{children:[(0,s.jsx)(t.strong,{children:"NEW"})," If a follower is restarted and has a corrupted snapshot it will detect it on bootstrap and will refuse to\nstart related services and crash. This means the pod will end in a crash loop, until this is manually fixed."]}),"\n",(0,s.jsxs)(t.p,{children:[(0,s.jsx)(t.strong,{children:"OLD"})," The follower only detects the corrupted snapshot on becoming leader when opening the database. On the restart of a follower this will not be detected."]}),"\n",(0,s.jsxs)(t.p,{children:["The behavior change caused to fail our automated chaos experiments, since we corrupt the snapshot on followers and on a later experiment we restart followers. For this reason we had to disable the execution of the snapshot corruption experiment, see related issue\n",(0,s.jsx)(t.a,{href:"https://github.com/zeebe-io/zeebe-cluster-testbench/issues/303",children:"zeebe-io/zeebe-cluster-testbench#303"}),"."]}),"\n",(0,s.jsxs)(t.p,{children:["In this chaos day we wanted to investigate whether we can improve the experiment and bring it back. For reference, I also opened a issue to discuss the current corruption detection approach ",(0,s.jsx)(t.a,{href:"https://github.com/camunda-cloud/zeebe/issues/6907",children:"zeebe#6907"})]}),"\n",(0,s.jsx)(t.h2,{id:"chaos-experiment",children:"Chaos Experiment"}),"\n",(0,s.jsx)(t.p,{children:"This time we look at an already existing experiment. I will run our normal setup and execute the experiment (each step) manually and observe what happens."}),"\n",(0,s.jsx)(t.h3,{id:"experiment",children:"Experiment"}),"\n",(0,s.jsx)(t.pre,{children:(0,s.jsx)(t.code,{className:"language-json",children:'{\n    "version": "0.1.0",\n    "title": "Zeebe can recover from corrupted snapshots",\n    "description": "Zeebe should be able to detect and recover from corrupted snapshot",\n    "contributions": {\n        "reliability": "high",\n        "availability": "high"\n    },\n    "steady-state-hypothesis": {\n        "title": "Zeebe is alive",\n        "probes": [\n            {\n                "name": "All pods should be ready",\n                "type": "probe",\n                "tolerance": 0,\n                "provider": {\n                    "type": "process",\n                    "path": "verify-readiness.sh",\n                    "timeout": 900\n                }\n            },\n            {\n                "name": "Should be able to create process instances on partition 3",\n                "type": "probe",\n                "tolerance": 0,\n                "provider": {\n                    "type": "process",\n                    "path": "verify-steady-state.sh",\n                    "arguments": "3",\n                    "timeout": 900\n                }\n            }\n        ]\n    },\n    "method": [\n        {\n            "type": "action",\n            "name": "Corrupt snapshots on followers",\n            "provider": {\n                "type": "process",\n                "path": "corruptFollowers.sh",\n                "arguments": "3"\n            }\n        },\n        {\n            "type": "action",\n            "name": "Terminate leader of partition 3",\n            "provider": {\n                "type": "process",\n                "path": "shutdown-gracefully-partition.sh",\n                "arguments": [ "Leader", "3" ]\n            }\n        }\n    ],\n    "rollbacks": []\n}\n'})}),"\n",(0,s.jsxs)(t.p,{children:["As written before we have our normal benchmark setup and I will run the referenced scripts manually and observe the behavior via grafana. The panels below show the base or steady state.\n",(0,s.jsx)(t.img,{alt:"before-general",src:n(61539).A+"",width:"1816",height:"572"}),"\n",(0,s.jsx)(t.img,{alt:"before-snap",src:n(53175).A+"",width:"1843",height:"645"})]}),"\n",(0,s.jsxs)(t.p,{children:["The first script we will run, corrupts for a certain partition the snapshots of all followers. It does it via just simply deleting some ",(0,s.jsx)(t.code,{children:"*.sst"})," files."]}),"\n",(0,s.jsx)(t.pre,{children:(0,s.jsx)(t.code,{className:"language-shell",children:"[zell scripts/ cluster: zeebe-cluster ns:zell-chaos]$ ./corruptFollowers.sh 3\n+ ...\n+ leader=zell-chaos-zeebe-1\n+ followers='zell-chaos-zeebe-0\nzell-chaos-zeebe-2'\n+ ...\n+ kubectl -n zell-chaos exec zell-chaos-zeebe-0 -- ./corrupting.sh 3\n+ partition=3\n+ partitionDir=data/raft-partition/partitions/3\n+ snapshotDir=(\"$partitionDir\"/snapshots/*)\n++ find data/raft-partition/partitions/3/snapshots/520492-1-1532470-1531619 -name '*.sst' -print -quit\n+ fileName=data/raft-partition/partitions/3/snapshots/520492-1-1532470-1531619/000110.sst\n+ rm data/raft-partition/partitions/3/snapshots/520492-1-1532470-1531619/000110.sst\n+ ...\n+ kubectl -n zell-chaos exec zell-chaos-zeebe-2 -- ./corrupting.sh 3\n+ partition=3\n+ partitionDir=data/raft-partition/partitions/3\n+ snapshotDir=(\"$partitionDir\"/snapshots/*)\n++ find data/raft-partition/partitions/3/snapshots/520492-1-1532470-1531619 -name '*.sst' -print -quit\n+ fileName=data/raft-partition/partitions/3/snapshots/520492-1-1532470-1531619/000112.sst\n+ rm data/raft-partition/partitions/3/snapshots/520492-1-1532470-1531619/000112.sst\n"})}),"\n",(0,s.jsx)(t.p,{children:"The second script just terminated the Leader for the referenced partition."}),"\n",(0,s.jsx)(t.pre,{children:(0,s.jsx)(t.code,{className:"language-shell",children:'[zell scripts/ cluster: zeebe-cluster ns:zell-chaos]$ ./terminate-partition.sh "Leader" 3\npod "zell-chaos-zeebe-1" deleted\n'})}),"\n",(0,s.jsx)(t.p,{children:'On the first try we had the "luck" that there was a snapshot replication in between, such that the follower was able to become Leader, since it had again a valid snapshot.'}),"\n",(0,s.jsxs)(t.p,{children:[(0,s.jsx)(t.img,{alt:"luck-general",src:n(89093).A+"",width:"1841",height:"649"}),"\n",(0,s.jsx)(t.img,{alt:"luck-replication",src:n(62623).A+"",width:"1832",height:"649"})]}),"\n",(0,s.jsx)(t.p,{children:"On the second try we were actually able to reproduce the behavior we want to see. We have corrupted the snapshot and restarted the Leader and the partition can make only progress - if the previous leader comes back. This is because the others have a corrupted snapshot and can't take over."}),"\n",(0,s.jsxs)(t.p,{children:[(0,s.jsx)(t.img,{alt:"no-luck-restart-general",src:n(84245).A+"",width:"1835",height:"645"}),"\n",(0,s.jsx)(t.img,{alt:"no-luck-restart",src:n(98386).A+"",width:"1837",height:"658"})]}),"\n",(0,s.jsx)(t.p,{children:"In all cases above we were able to make progress. The issue now arises when one of the affected follower is restarted. For our experiment I restarted Broker-2, which was at this point in time follower for Partition 3. After I restarted the follower it first looked like the partition one was completely down."}),"\n",(0,s.jsx)(t.p,{children:(0,s.jsx)(t.img,{alt:"follower-restart-partition-1",src:n(54278).A+"",width:"1831",height:"653"})}),"\n",(0,s.jsx)(t.p,{children:"After serveral minutes the system recovered and continued."}),"\n",(0,s.jsx)(t.p,{children:(0,s.jsx)(t.img,{alt:"follower-restart-partition-1-cont",src:n(70525).A+"",width:"1814",height:"613"})}),"\n",(0,s.jsxs)(t.p,{children:["Via Grafana but also via ",(0,s.jsx)(t.code,{children:"kubectl"})," we can see that the pod doesn't become ready again."]}),"\n",(0,s.jsx)(t.pre,{children:(0,s.jsx)(t.code,{className:"language-shell",children:"zell-chaos-zeebe-0                          1/1     Running     0          13m\nzell-chaos-zeebe-1                          1/1     Running     0          17m\nzell-chaos-zeebe-2                          0/1     Running     0          5m4s\nzell-chaos-zeebe-gateway-854dd5dd5c-b8cpl   1/1     Running     0          45m\n"})}),"\n",(0,s.jsx)(t.pre,{children:(0,s.jsx)(t.code,{className:"language-shell",children:"  Warning  Unhealthy               4m59s               kubelet                  Readiness probe failed: HTTP probe failed with statuscode: 503\n  Warning  Unhealthy               9s (x30 over 5m9s)  kubelet                  Readiness probe failed: Get http://10.0.29.26:9600/ready: dial tcp 10.0.29.26:9600: connect: connection refused\n"})}),"\n",(0,s.jsxs)(t.p,{children:["In camunda cloud this will end in a crash loop, because we restart pods after 15 minutes if they are not ready in time. It is interesting to see that it seems not to restart by itself, ",(0,s.jsx)(t.strong,{children:"which I had expected"}),". After checking the logs we can also see why."]}),"\n",(0,s.jsx)(t.pre,{children:(0,s.jsx)(t.code,{className:"language-md",children:"I 2021-04-29T11:20:44.205851Z RaftServer{raft-partition-partition-1} - Server join completed. Waiting for the server to be READY \n**W 2021-04-29T11:20:44.220338Z Cannot load snapshot in /usr/local/zeebe/data/raft-partition/partitions/3/snapshots/1387684-4-4014493-4014014. The checksum stored does not match the checksum calculated.** \nD 2021-04-29T11:20:44.737724Z Loaded disk segment: 33 (raft-partition-partition-3-33.log) \nD 2021-04-29T11:20:44.738579Z Found segment: 33 (raft-partition-partition-3-33.log) \nD 2021-04-29T11:20:45.024028Z Loaded disk segment: 34 (raft-partition-partition-3-34.log) \nD 2021-04-29T11:20:45.024688Z Found segment: 34 (raft-partition-partition-3-34.log) \nE 2021-04-29T11:20:45.025826Z Bootstrap Broker-2 [6/13]: cluster services failed with unexpected exception. \nI 2021-04-29T11:20:45.038260Z Closing Broker-2 [1/5]: subscription api \nD 2021-04-29T11:20:45.040467Z Closing Broker-2 [1/5]: subscription api closed in 1 ms \nI 2021-04-29T11:20:45.040926Z Closing Broker-2 [2/5]: command api handler \nD 2021-04-29T11:20:45.042116Z Closing Broker-2 [2/5]: command api handler closed in 1 ms \nI 2021-04-29T11:20:45.042524Z Closing Broker-2 [3/5]: command api transport \nD 2021-04-29T11:20:46.163435Z Created segment: JournalSegment{id=2, index=1556849} \nI 2021-04-29T11:20:47.065203Z Stopped \nD 2021-04-29T11:20:47.066007Z Closing Broker-2 [3/5]: command api transport closed in 2023 ms \nI 2021-04-29T11:20:47.066552Z Closing Broker-2 [4/5]: membership and replication protocol \nE 2021-04-29T11:20:47.067664Z Closing Broker-2 [4/5]: membership and replication protocol failed to close. \nI 2021-04-29T11:20:47.069050Z Closing Broker-2 [5/5]: actor scheduler \nD 2021-04-29T11:20:47.069503Z Closing actor thread ground 'Broker-2-zb-fs-workers' \nD 2021-04-29T11:20:47.071276Z Closing actor thread ground 'Broker-2-zb-fs-workers': closed successfully \nD 2021-04-29T11:20:47.071642Z Closing actor thread ground 'Broker-2-zb-actors' \nD 2021-04-29T11:20:47.073287Z Closing actor thread ground 'Broker-2-zb-actors': closed successfully \nD 2021-04-29T11:20:47.074101Z Closing Broker-2 [5/5]: actor scheduler closed in 4 ms \nI 2021-04-29T11:20:47.074468Z Closing Broker-2 succeeded. Closed 5 steps in 2036 ms. \n**E 2021-04-29T11:20:47.074845Z Failed to start broker 2!** \nI 2021-04-29T11:20:47.078669Z \n\nError starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled. \n**E 2021-04-29T11:20:47.093828Z Application run failed** \nI 2021-04-29T11:20:47.120419Z Shutting down ExecutorService 'applicationTaskExecutor' \nI 2021-04-29T11:20:47.132016Z RaftServer{raft-partition-partition-1}{role=FOLLOWER} - No heartbeat from null in the last PT2.926S (calculated from last 2926 ms), sending poll requests \nI 2021-04-29T11:20:47.260582Z RaftServer{raft-partition-partition-1} - Found leader 0 \nI 2021-04-29T11:20:47.262407Z RaftServer{raft-partition-partition-1} - Setting firstCommitIndex to 1507899. RaftServer is ready only after it has committed events upto this index \nI 2021-04-29T11:20:47.263428Z RaftPartitionServer{raft-partition-partition-1} - Successfully started server for partition PartitionId{id=1, group=raft-partition} in 10098ms \nD 2021-04-29T11:21:05.128572Z Created segment: JournalSegment{id=3, index=1570617} \nD 2021-04-29T11:21:26.376398Z Created segment: JournalSegment{id=4, index=1584886} \nI 2021-04-29T11:21:28.129677Z RaftPartitionServer{raft-partition-partition-2} - Successfully started server for partition PartitionId{id=2, group=raft-partition} in 51572ms \n"})}),"\n",(0,s.jsxs)(t.p,{children:["We can see in the logs that the corruption is detected and the broker seems to stop, but actually it doesn't.\nAfter ",(0,s.jsx)(t.code,{children:"Failed to start broker 2"})," the process should normally end. It looks like the thread for the other raft partitions are still running and continuing. This is a bug which I reported in one of my last chaos days,\nsee ",(0,s.jsx)(t.a,{href:"https://github.com/camunda-cloud/zeebe/issues/6702",children:"camunda-cloud/zeebe#6702"}),"."]}),"\n",(0,s.jsx)(t.p,{children:"With this current behavior we could easily fix the snapshot corruption experiments, since we just need a separate clean up step. It could look like this:"}),"\n",(0,s.jsx)(t.pre,{children:(0,s.jsx)(t.code,{className:"language-shell",children:" k exec -it zell-chaos-zeebe-2 -- rm -r data/raft-partition/partitions/3 # remove partition three data\n k delete pod zell-chaos-zeebe-2 # restart broker 2\n"})}),"\n",(0,s.jsx)(t.p,{children:"I tried this and it worked, after some minutes the Broker-2 was able to come back."}),"\n",(0,s.jsx)(t.p,{children:(0,s.jsx)(t.img,{alt:"success-after-fix.png",src:n(89731).A+"",width:"1824",height:"647"})}),"\n",(0,s.jsx)(t.p,{children:"Why does it work you may ask. If we remove the corrupted partition data from the follower and restart it, then it will join the cluster with an empty state. The Leader for that partition will immediately replicate the snapshot for that partition, such that the follower is up to date again. This allows the follower then to bootstrap without issues again."}),"\n",(0,s.jsxs)(t.p,{children:["One problem with this approach we have if we actually fix the bug above, where we're not shutting down, then we have the issue that we might not be able to access the data, since the pod is not up. I need to do some more research to solve this, but one possible solution I can think of would be to patch the ",(0,s.jsx)(t.em,{children:"StatefulSet"}),", such that we can claim the PV via multiple pods. This would allow us to start a separate POD in order to access the data and delete it."]}),"\n",(0,s.jsx)(t.h2,{id:"found-bugs",children:"Found Bugs"}),"\n",(0,s.jsxs)(t.ul,{children:["\n",(0,s.jsxs)(t.li,{children:["Broker is not shutting down properly ",(0,s.jsx)(t.a,{href:"https://github.com/camunda-cloud/zeebe/issues/6702",children:"camunda-cloud/zeebe#6702"})]}),"\n"]})]})}function d(e={}){const{wrapper:t}={...(0,r.R)(),...e.components};return t?(0,s.jsx)(t,{...e,children:(0,s.jsx)(c,{...e})}):c(e)}},61539:(e,t,n)=>{n.d(t,{A:()=>a});const a=n.p+"assets/images/before-general-c5e2d4a84d58bfe92397a1950bce66ab.png"},53175:(e,t,n)=>{n.d(t,{A:()=>a});const a=n.p+"assets/images/before-snap-af75897dcbf32d097c6a0e79300c23fd.png"},70525:(e,t,n)=>{n.d(t,{A:()=>a});const a=n.p+"assets/images/follower-restart-partition-1-cont-9ea01572ab691821683a0145afeb5c80.png"},54278:(e,t,n)=>{n.d(t,{A:()=>a});const a=n.p+"assets/images/follower-restart-partition-1-196eaa9f08944822a7eb9bc3e10b3aa1.png"},89093:(e,t,n)=>{n.d(t,{A:()=>a});const a=n.p+"assets/images/luck-general-6284a961fb55242e685ef99a31487f34.png"},62623:(e,t,n)=>{n.d(t,{A:()=>a});const a=n.p+"assets/images/luck-replication-2564925f2731e3c9b5279a8db021b902.png"},84245:(e,t,n)=>{n.d(t,{A:()=>a});const a=n.p+"assets/images/no-luck-restart-general-1f6e7cdad4128ad263669bf62557bb4f.png"},98386:(e,t,n)=>{n.d(t,{A:()=>a});const a=n.p+"assets/images/no-luck-restart-556f37ee3d483e799428e83ad20d1aa5.png"},89731:(e,t,n)=>{n.d(t,{A:()=>a});const a=n.p+"assets/images/success-after-fix-6c7506d3368e85a046fc4d0745965292.png"},28453:(e,t,n)=>{n.d(t,{R:()=>o,x:()=>i});var a=n(96540);const s={},r=a.createContext(s);function o(e){const t=a.useContext(r);return a.useMemo((function(){return"function"==typeof e?e(t):{...t,...e}}),[t,e])}function i(e){let t;return t=e.disableParentContext?"function"==typeof e.components?e.components(s):e.components||s:o(e.components),a.createElement(r.Provider,{value:t},e.children)}},85091:e=>{e.exports=JSON.parse('{"permalink":"/zeebe-chaos/2021/04/29/Corrupted-Snapshot","editUrl":"https://github.com/zeebe-io/zeebe-chaos/blob/master/chaos-days/blog/2021-04-29-Corrupted-Snapshot/index.md","source":"@site/blog/2021-04-29-Corrupted-Snapshot/index.md","title":"Corrupted Snapshot Experiment Investigation","description":"A while ago we have written an experiment, which should verify that followers are not able to become leader, if they have a corrupted snapshot. You can find that specific experiment here. This experiment was executed regularly against Production-M and Production-S Camunda Cloud cluster plans. With the latest changes, in the upcoming 1.0 release, we changed some behavior in regard to detect snapshot corruption on followers.","date":"2021-04-29T00:00:00.000Z","tags":[{"inline":true,"label":"availability","permalink":"/zeebe-chaos/tags/availability"}],"readingTime":7.195,"hasTruncateMarker":true,"authors":[{"name":"Christopher Kujawa","title":"Chaos Engineer @ Zeebe","url":"https://github.com/ChrisKujawa","page":{"permalink":"/zeebe-chaos/authors/zell"},"imageURL":"https://github.com/ChrisKujawa.png","key":"zell"}],"frontMatter":{"layout":"posts","title":"Corrupted Snapshot Experiment Investigation","date":"2021-04-29T00:00:00.000Z","categories":["chaos_experiment","broker","snapshots"],"tags":["availability"],"authors":"zell"},"unlisted":false,"prevItem":{"title":"Time travel Experiment","permalink":"/zeebe-chaos/2021/05/25/Reset-Clock"},"nextItem":{"title":"BPMN meets Chaos Engineering","permalink":"/zeebe-chaos/2021/04/03/bpmn-meets-chaos-engineering"}}')}}]);